# Generic Settings
version: '{build}-{branch}'
max_jobs: 2
clone_depth: 1

# Build Image & Environment
platform: x64

matrix:
  fast_finish: true

environment:
  global: 
    CURL_VERSION: 7.56.1
    CEF_VERSION: 3.3440.1805.gbe070f9
    APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: "Ubuntu"
    CMAKE_GENERATOR_64: "Unix Makefiles"
    VERSION_OVERRIDE: "0.0.0.0-gcc"
    COMPILER_FLAGS_64: -m64
  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    CMAKE_GENERATOR_32: "Visual Studio 15 2017"
    CMAKE_GENERATOR_64: "Visual Studio 15 2017 Win64"
    CMAKE_SYSTEM_VERSION: "10.0.17134.0"
    VERSION_OVERRIDE: "0.0.0.0-vs2017"

cache:
  - dependencies2017.zip
  - vlc.zip
  - 'cef_binary_%CEF_VERSION%_windows32.zip'
  - 'cef_binary_%CEF_VERSION%_windows64.zip'

install:
  - git submodule update --init --recursive
  - cmd: ./CI/xaymar/install-win.cmd
  - sh: ./CI/xaymar/install-ubuntu16.sh

build_script:
  - cmd: node ./CI/xaymar/builder.js
  - sh: node ./CI/xaymar/builder.js

test: off

artifacts:
  - path: build32/*.7z
  - path: build64/*.7z

deploy:
- provider: GitHub
  auth_token:
    secure: vushyTq6uZybHo5y1EFXQ4Ze6RSGF8TeKWjpQavc20MJRYHCZcIyc55BmY2Cfc7z
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true

notifications:
- provider: Webhook
  url:
    secure: PTtt5ALhmK0q42jYyx4/Qa1Uf18+gLMXKGdzJjDISJsLoTbnbjJs20iYKkdkXzjCxz4P+OtNsDAlcvpt22zFFaDx+DKfX3WrKdupfw3uW+DJzaIkFZ1njl4NRC3v2ZieNekM6fFm0uoql9sz13hWQ/XKfmq2WQf6hHJ9rO1FluU=
  method: POST
  body: >-
    {
      "content": "**Build {{status}}**: {{buildUrl}}\n[{{commitId}}] {{commitMessage}}\nBy {{commitAuthor}} on {{commitDate}}"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
