name: CI

on: [push, pull_request]

env:
  CEF_VERSION: "75.1.16+g16a67c4+chromium-75.0.3770.100"

jobs:
  win32:
    name: "Windows 32-bit"
    runs-on: windows-2019
    env:
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_SYSTEM_VERSION: "10.0.18363.657"
      VERSION_OVERRIDE: "0.0.0.0-vs2019"
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: "QT"
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_msvc2017'
        dir: '${{ github.workspace }}/cmbuild/'
    - name: "Prerequisites: Submodules"
      shell: bash
      run: git submodule update --init --recursive
    - name: "Prerequisites: Dependencies"
      shell: bash
      run: |
        curl -kL "https://cdn.xaymar.com/obs/dependencies_25.0.0.zip" -f --retry 5 -o dependencies2017.zip
        7z x dependencies2017.zip -o"${{ github.workspace }}/cmbuild/deps"
    - name: "Prerequisites: VLC"
      shell: bash
      run: |
        curl -kL https://cdn-fastly.obsproject.com/downloads/vlc.zip -f --retry 5 -o vlc.zip
        7z x vlc.zip -o"${{ github.workspace }}/cmbuild/vlc"
    - name: "Prerequisites: Chromium Embedded Framework"
      shell: bash
      run: |
        curl -kL https://cdn-fastly.obsproject.com/downloads/cef_binary_${{ env.CEF_VERSION }}_windows32_minimal.zip -f --retry 5 -o cef.zip
        7z x cef.zip -o"${{ github.workspace }}/cmbuild"
    - name: "Configure"
      shell: bash
      run: |
        cmake -H. -Bbuild32 -G"${{ env.CMAKE_GENERATOR }}" -A"Win32" -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" -DBUILD_AMD_ENCODER=true -DBUILD_BROWSER=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true -DCOMPILE_LUA=true -DCOMPILE_PYTHON=true -DDepsPath="${{ github.workspace }}/cmbuild/deps/win32" -DQTDIR="${{ github.workspace }}/QT/5.14.1/msvc2017" -DCEF_ROOT_DIR="${{ github.workspace }}/cef_binary_${{ env.CEF_VERSION}}_windows32_minimal" -DCPACK_GENERATOR=7Z -DCPACK_SOURCE_GENERATOR=7Z -DCOPIED_DEPENDENCIES=FALSE -DCOPY_DEPENDENCIES=true -DOBS_VERSION_OVERRIDE="${{ env.VERSION_OVERRIDE }}"
    - name: "Build"
      shell: bash
      run: |
        cmake --build build32 --config RelWithDebInfo --target PACKAGE
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v2-preview
      with:
        path: build32/*.7z
  win64:
    name: "Windows 64-bit"
    runs-on: windows-2019
    env:
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_SYSTEM_VERSION: "10.0.18363.657"
      VERSION_OVERRIDE: "0.0.0.0-vs2019"
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: "QT"
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/cmbuild/'
    - name: "Prerequisites: Submodules"
      shell: bash
      run: git submodule update --init --recursive
    - name: "Prerequisites: Dependencies"
      shell: bash
      run: |
        curl -kL "https://cdn.xaymar.com/obs/dependencies_25.0.0.zip" -f --retry 5 -o dependencies2017.zip
        7z x dependencies2017.zip -o"${{ github.workspace }}/cmbuild/deps"
    - name: "Prerequisites: VLC"
      shell: bash
      run: |
        curl -kL https://cdn-fastly.obsproject.com/downloads/vlc.zip -f --retry 5 -o vlc.zip
        7z x vlc.zip -o"${{ github.workspace }}/cmbuild/vlc"
    - name: "Prerequisites: Chromium Embedded Framework"
      shell: bash
      run: |
        curl -kL https://cdn-fastly.obsproject.com/downloads/cef_binary_${{ env.CEF_VERSION }}_windows64_minimal.zip -f --retry 5 -o cef.zip
        7z x cef.zip -o"${{ github.workspace }}/cmbuild"
    - name: "Configure"
      shell: bash
      run: |
        cmake -H. -Bbuild64 -G"${{ env.CMAKE_GENERATOR }}" -A"x64" -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" -DBUILD_AMD_ENCODER=true -DBUILD_BROWSER=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=true -DCOMPILE_LUA=true -DCOMPILE_PYTHON=true -DDepsPath="${{ github.workspace }}/cmbuild/deps/win64" -DQTDIR="${{ github.workspace }}/QT/5.14.1/msvc2017_64" -DCEF_ROOT_DIR="${{ github.workspace }}/cef_binary_${{ env.CEF_VERSION}}_windows64_minimal" -DCPACK_GENERATOR=7Z -DCPACK_SOURCE_GENERATOR=7Z -DCOPIED_DEPENDENCIES=FALSE -DCOPY_DEPENDENCIES=true -DOBS_VERSION_OVERRIDE="${{ env.VERSION_OVERRIDE }}"
    - name: "Build"
      shell: bash
      run: |
        cmake --build build64 --config RelWithDebInfo --target PACKAGE
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v2-preview
      with:
        path: build64/*.7z
